id: I3ED4DA67
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T10:30:54+00:00'
last_modified: '2022-06-07T15:03:28.800012+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD397
  title: མཐིང་མུ་ནི་ལྷ་རྫོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6941':
      image_group_id: I2PD17698
      title: ''
      total_pages: 586
      order: 1
      base_file: 6941.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
