id: P001761
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:19:52.004672
source_metadata:
  id: bdr:W3PD397
  title: མཐིང་མུ་ནི་ལྷ་རྫོང་།
  author: ''
  volumes:
    90fd4c517ea34fe39ca860cdba5a15de:
      image_group_id: I2PD17698
      title: ''
      volume_number: 1
      total_pages: 586
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
